name: zh_cn_utils
version: 1.0.0
homepage: https://github.com/Little-Star-Star/zh_cn_utils.git
description: A chinese handle utils.
authors:
  - liguoliang<3010972113@qq.com>
environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
